# Generated by Django 4.2.7 on 2023-11-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='custom_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarbonFootprintData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_mode', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight')], max_length=50)),
                ('distance_traveled', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fuel_efficiency', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('number_of_passengers', models.PositiveIntegerField(default=1)),
                ('aircraft_type', models.CharField(blank=True, max_length=50, null=True)),
                ('diet_type', models.CharField(choices=[('omnivorous', 'Omnivorous'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], max_length=50)),
                ('food_origin', models.CharField(choices=[('local', 'Local'), ('imported', 'Imported')], max_length=50)),
                ('total_waste_generated', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('recyclable_materials_recycled', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('organic_waste_composted', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('electricity_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('heating_cooling_energy_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('household_size', models.PositiveIntegerField(default=1)),
                ('renewable_energy_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('electricity_source', models.CharField(blank=True, choices=[('coal', 'Coal'), ('natural_gas', 'Natural Gas'), ('renewable', 'Renewable Energy'), ('other', 'Other')], max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
        ),
    ]
